(function() {
  'use strict';

  angular.module(
    'ngMaterial', [
    "ng",
    "ngAnimate",
    "ngAria",
    "material.core",
    "material.core.gestures",
    "material.core.layout",
    "material.core.theming.palette",
    "material.core.theming",
    "material.core.animate",
    // "material.components.autocomplete",
    "material.components.backdrop",
    // "material.components.bottomSheet",
    "material.components.button",
    // "material.components.card",
    "material.components.checkbox",
    // "material.components.chips",
    // "material.components.content",
    // "material.components.datepicker",
    "material.components.dialog",
    // "material.components.divider",
    // "material.components.fabActions",
    // "material.components.fabShared",
    // "material.components.fabSpeedDial",
    // "material.components.fabToolbar",
    // "material.components.fabTrigger",
    // "material.components.gridList",
    "material.components.icon",
    "material.components.input",
    "material.components.list",
    "material.components.menu",
    "material.components.menuBar",
    "material.components.progressCircular",
    // "material.components.progressLinear",
    // "material.components.checkbox",
    // "material.components.radioButton",
    "material.components.select",
    // "material.components.showHide",
    // "material.components.sidenav",
    // "material.components.slider",
    "material.components.sticky",
    "material.components.content",
    "material.components.subheader",
    // "material.components.swipe",
    // "material.components.switch",
    // "material.components.tabs",
    "material.components.toast",
    "material.components.panel",
    // "material.components.toolbar",
    "material.components.tooltip",
    // "material.components.virtualRepeat",
    // "material.components.whiteframe"
    ]);
})();